site_name: FIX
nav:
 - Home: index.md
 - Trading messages:
   - NewOrderSingle: NewOrderSingle.md
   - ExecutionReport: ExecutionReport.md
   - CancelRequest: CancelRequest.md
 - Message components:
   - Standard header: StandardHeader.md
 - Document changelog: ver.md
theme:
   name: material
   palette:
     - scheme: default
       toggle:
         icon: material/brightness-7
         name: Switch to dark
       primary: teal
     - scheme: slate
       toggle:
         icon: material/brightness-4
         name: Switch to light
       primary: teal
   features: 
    - navigation.tabs
markdown_extensions:
 - tables
 - markdown_include.include:
    base_path: docs
